/* Generated by cbindgen — do not edit manually. */

#ifndef BYBLOS_CORE_H
#define BYBLOS_CORE_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Target sample rate for all speech recognition models.
 */
#define TARGET_SAMPLE_RATE 16000

/**
 * Opaque handle to a Byblos pipeline instance.
 */
typedef struct ByblosHandle ByblosHandle;

/**
 * Create a new Byblos instance with the given model path.
 *
 * Returns a pointer to the handle, or null on failure.
 * Caller must eventually call `byblos_destroy` to free.
 */
struct ByblosHandle *byblos_create(const char *model_path);

/**
 * Start recording audio.
 */
bool byblos_start_recording(struct ByblosHandle *handle);

/**
 * Stop recording and begin transcription.
 *
 * Returns the transcribed text as a C string. Caller must free with `byblos_free_string`.
 */
char *byblos_stop_recording(struct ByblosHandle *handle);

/**
 * Free a string returned by byblos functions.
 */
void byblos_free_string(char *s);

/**
 * Destroy a Byblos instance and free all resources.
 */
void byblos_destroy(struct ByblosHandle *handle);

#endif  /* BYBLOS_CORE_H */
